swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Swagger Petstore
  license:
    name: MIT
  contact:
    name: Test
paths:
  /pets/{petId}:
    post:
      parameters:
        - in: body
          name: petId
          schema:
            type: integer
            example: 123
          example: 23
      responses:
        200:
          description: ok
